ros2 bag record \
    /aruco/images \
    /aruco/markers \
    /aruco/poses \
    /cameraswingmotor/angle \
    /cameraswingmotor/target_angle \
    /chokudomotor/angle \
    /chokudomotor/target_angle \
    /clicked_point \
    /detected_depth_points \
    /goal_pose \
    /initialpose \
    /motor_angles \
    /motor_current_angles \
    /parameter_events \
    /rosout \
    /sensor/pressure \
    /hose/goal_point \
    /switch \
    /tf \
    /tf_static \
    /relay_switch \
    /sensor/pressure \
    /start_grasp \
    /vacuum_flag \
